import os
import ftplib

FTP_SERVER = "ftp.revista.lat"
FTP_USER = "ivanramos@app.doggogo.site"
FTP_PASS = "Lallave2026."
PORT = 21
LOCAL_DIR = "dist" # The folder generated by expo export

def upload_directory(ftp, local_dir, remote_dir):
    try:
        ftp.mkd(remote_dir)
    except ftplib.error_perm:
        pass # Directory might already exist

    ftp.cwd(remote_dir)

    for item in os.listdir(local_dir):
        local_path = os.path.join(local_dir, item)
        if os.path.isfile(local_path):
            with open(local_path, 'rb') as f:
                print(f"Uploading file: {item}")
                ftp.storbinary(f'STOR {item}', f)
        elif os.path.isdir(local_path):
            print(f"Uploading directory: {item}")
            upload_directory(ftp, local_path, item)
            ftp.cwd("..") # Go back up

def clear_directory(ftp, path):
    try:
        ftp.cwd(path)
        files = ftp.nlst()
        for f in files:
            if f in ('.', '..'): continue
            try:
                ftp.delete(f)
                print(f"Deleted file {f}")
            except ftplib.error_perm:
                try:
                    clear_directory(ftp, f)
                    ftp.rmd(f)
                    print(f"Deleted directory {f}")
                except Exception as e:
                    print(f"Could not delete {f}: {e}")
        ftp.cwd('..')
    except Exception as e:
        print(f"Could not clear directory {path}: {e}")

def main():
    print(f"Connecting to {FTP_SERVER}...")
    try:
        ftp = ftplib.FTP()
        ftp.connect(FTP_SERVER, PORT, timeout=10)
        ftp.login(FTP_USER, FTP_PASS)
        print("Logged in successfully.")
        
        ftp.cwd('/')
        print("Clearing existing files...")
        clear_directory(ftp, '/')
        ftp.cwd('/')
        
        if not os.path.exists(LOCAL_DIR):
            print(f"Error: {LOCAL_DIR} does not exist.")
            return

        print("Starting upload...")
        for item in os.listdir(LOCAL_DIR):
            local_path = os.path.join(LOCAL_DIR, item)
            if os.path.isfile(local_path):
                with open(local_path, 'rb') as f:
                    print(f"Uploading file: {item}")
                    ftp.storbinary(f'STOR {item}', f)
            elif os.path.isdir(local_path):
                print(f"Uploading directory: {item}")
                upload_directory(ftp, local_path, item)
                ftp.cwd("/")

        ftp.quit()
        print("Upload complete.")
    except Exception as e:
        print(f"FTP Error: {e}")

if __name__ == "__main__":
    main()
